# Model architecture
model:
    type: "track_classifier"
    hit_input_dim: 9
    track_feat_dim: 25
    latent_dim: 16
    pooling_type: "sum"

    netA:
        kind: "mlp"
        hidden_dim: 32
        hidden_layers: 2
        batchnorm: True
        activation: "silu"

    netB:
        kind: "mlp"
        hidden_dim: 64
        hidden_layers: 2
        batchnorm: True
        activation: "silu"

# Training setup
training:
    epochs: 5
    batch_size: 128
    patience: 15
    delta: 0
    base_checkpoint_directory: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/runs"

    symmetry:
        idxSymRecHitFeatures: [2, 7]
        idxSymRecoPixelTrackFeatures: [5, 7, 10, 22, 23]
        lambda_sym: 0.1
    
    weights:
        w_true: 0.60 
        w_fake: 2.91

    optimizer:
        name: 'adam'
        lr: 1.e-3
        weight_decay: 0
    
    scheduler:
        name: 'none'

# Data
data:
    dataset_type: "production"          # or 'production'
    train_path: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/tracks_train_dataset.pt"  # used only if production
    val_path: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/tracks_val_dataset.pt"
    test_path: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/tracks_test_dataset.pt"
    max_hits: 16