model:
  type: track_classifier
  hit_input_dim: 8
  track_feat_dim: 12
  latent_dim: 16
  pooling_type: mean
  netA:
    kind: mlp
    hidden_dim: 64
    hidden_layers: 2
    batchnorm: true
    activation: relu
  netB:
    kind: mlp
    hidden_dim: 32
    hidden_layers: 3
    batchnorm: true
    activation: relu
training:
  epochs: 75
  batch_size: 128
  patience: 15
  delta: 0.0
  base_checkpoint_directory: /eos/user/e/ecoradin/GitHub/TrackSelectorDNN/runs-noHitPattern-skipping-GPU
  optimizer:
    name: adam
    lr: 0.004960155501949429
    weight_decay: 6.057427974775773e-06
  scheduler:
    name: none
    min_lr: null
    factor: null
    patience: null
    T_max: null
    eta_min: null
    max_lr: null
    pct_start: null
    anneal_strategy: null
    div_factor: null
    final_div_factor: null
    three_phase: null
  symmetry:
    idxSymRecHitFeatures: null
    idxSymRecoPixelTrackFeatures: null
    idxSymPreselectFeatures: null
    lambda_sym: null
  weights:
    w_true: 2.18
    w_fake: 0.65
data:
  dataset_type: production
  dummy_load_path: null
  train_path: /eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/100_tracks_train_dataset_skip-connections_GNN_v2.pt
  val_path: /eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/100_tracks_val_dataset_skip-connections_GNN_v2.pt
  test_path: null
  max_hits: 16
