# Model architecture
hit_input_dim: 9
track_feat_dim: 23
latent_dim: 16
pooling_type: "sum"

netA_hidden_dim: 32
netA_hidden_layers: 2
netA_batchnorm: True
netA_activation: "silu"

netB_hidden_dim: 64
netB_hidden_layers: 2
netB_batchnorm: True
netB_activation: "silu"

# Training setup
lr: 1.e-3
weight_decay: 0
epochs: 5
batch_size: 128
patience: 15
delta: 0
: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/runs"

# Data
dataset_type: "production"          # or 'production'
train_path: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/tracks_train_dataset.pt"  # used only if production
val_path: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/tracks_val_dataset.pt"
test_path: "/eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/tracks_test_dataset.pt"
max_hits: 16