model:
  type: track_classifier
  hit_input_dim: 8
  track_feat_dim: 12
  latent_dim: 16
  pooling_type: mean
  netA:
    kind: mlp
    hidden_dim: 64
    hidden_layers: 2
    batchnorm: true
    activation: relu
  netB:
    kind: mlp
    hidden_dim: 32
    hidden_layers: 3
    batchnorm: true
    activation: relu
training:
  epochs: 80
  batch_size: 512
  patience: 100
  delta: 0
  base_checkpoint_directory: /eos/user/e/ecoradin/GitHub/TrackSelectorDNN/runs-grid-long-GPU
  optimizer:
    name: adam
    lr: 0.00025
    weight_decay: 4.45e-07
  scheduler:
    name: onecycle
    max_lr: 0.001         # ~10Ã— base lr
    pct_start: 0.1        
    anneal_strategy: cos  # cosine decay
    div_factor: 10.0      # initial_lr = max_lr / 10
    final_div_factor: 100 # final_lr = initial_lr / 100
    three_phase: false
  symmetry:
    idxSymRecHitFeatures: null
    idxSymRecoPixelTrackFeatures: null
    idxSymPreselectFeatures: null
    lambda_sym: null
  weights:
    w_true: 0.77
    w_fake: 1.42
  reweighting:
    enable: false
    feature: "hltPixelTrack_eta"
    n_bins: 50
    do_class_norm: true  
data:
  dataset_type: production
  dummy_load_path: null
  train_path: /eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/1000_tracks_train_dataset_skip-connections_strict_chi2_GNN.pt
  val_path: /eos/user/e/ecoradin/GitHub/TrackSelectorDNN/TrackSelectorDNN/data/1000_tracks_val_dataset_skip-connections_strict_chi2_GNN.pt
  test_path: null
  max_hits: 16
